ersion: "3.9"


services:
  db:
    image: mysql:5.7
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=luna1503
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=felipe
      - MYSQL_PASSWORD=luna1503


  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - ./wordpress_data:/var/www/html
    ports:
      - "8000:80"
    restart: always
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=felipe
      - WORDPRESS_DB_PASSWORD=luna1503
      - WORDPRESS_DB_NAME=wordpress
