version: "3.9"


services:

  portainer:
    image: portainer/portainer-ce:2.6.0
    ports:
      - 88:9000
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: bind
        source: ./data/portainer
        target: /data
    # deploy:
    #   replicas: 1
    #   restart_policy:
    #     condition: on-failure
    #   placement:
    #     constraints:
    #       - node.role == manager
    #   update_config:
    #     order: start-first
    #     delay: 1m
    #     parallelism: 1
    #     failure_action: rollback